name: Release
on: push

env:
  golang-version: '1.24.1'
  units-geth-tag: '853c4e425e435fd09b05502cc863ae170ef2aff5'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
        - os: windows-latest
          platform: win64
          aext: zip
        - os: ubuntu-22.04
          platform: linux
          aext: tgz
        - os: macos-latest
          platform: darwin
          aext: tgz

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      env:
        TARGET: ${{ env.units-geth-tag }}
      shell: bash
      run: |
        mkdir units-geth
        cd units-geth
        git init -q .
        git remote add origin https://github.com/deemru/op-geth.git
        git fetch origin ${TARGET}
        git checkout -b temp ${TARGET}
        git tag -f "${GITHUB_REF_NAME}-units"

    - name: Go Setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.golang-version }}
        cache-dependency-path: units-geth/go.sum

    - name: Go Build
      shell: bash
      run: |
        cd units-geth
        go run build/ci.go install ./cmd/geth
        build/bin/geth version

    - name: Compress
      if: startsWith(github.ref, 'refs/tags/')
      env:
        PLATFORM: ${{ matrix.platform }}
        AEXT: ${{ matrix.aext }}
      shell: bash
      run: |
        cd units-geth/build/bin
        if [ "$RUNNER_OS" == "Windows" ]; then
          7z a -mm=Deflate -mfb=258 -mpass=15 -r units-geth-${GITHUB_REF_NAME}_${PLATFORM}.${AEXT} ./geth.exe
        elif [ "$RUNNER_OS" == "Linux" ]; then
          tar -cvf units-geth-${GITHUB_REF_NAME}_${PLATFORM}.${AEXT} --use-compress-program='gzip -9' ./geth
        elif [ "$RUNNER_OS" == "macOS" ]; then
          tar -cvf units-geth-${GITHUB_REF_NAME}_${PLATFORM}.${AEXT} --use-compress-program='gzip -9' ./geth
        else
          exit 1
        fi

    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          units-geth/build/bin/units-geth-${{ github.ref_name }}_${{ matrix.platform }}.${{ matrix.aext }}
